import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/WEIGHTSCALE.jpg',
    title: 'Electronic Weighing Scale',
    rating: 5,
    ratingCount: 9,
    price: 10,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/IMG_1089.jpg',
    title: 'CCTV CAMERAS',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/IMG_1092.jpg',
    title: 'JEWELLERY',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/IMG_1093.jpg',
    title: 'HANDCRAFTS',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/IMG_1090.jpg',
    title: 'Gold Testing Machine',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/courses/IMG_1091.jpg',
    title: 'Note Counting Machine',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/courses/IMG_1094.jpg',
    title: 'GPS TRACKING',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
]
